{% set name = "validator-collection" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/validator-collection-{{ version }}.tar.gz
  sha256: f9395cad9a30cb9864fa0c0d18a84daead1eb8807774f4e09f588f89b7dc77d8

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - jsonschema
    - python >={{ python_min }},<4.0

test:
  imports:
    - validator_collection
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/insightindustry/validator-collection
  summary: Collection of 60+ Python functions for validating data
  dev_url: https://github.com/insightindustry/validator-collection/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacpete
